In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("students.csv")

In [ ]:
df

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
1    Ahmed   21     72     Lahore
2      Ali   20     91    Karachi
3    Usman   22     65  Islamabad
4    Hamza   21     78     Lahore
5   Ayesha   20     95    Karachi
6    Bilal   23     55  Islamabad
7  Mahnoor   21     88     Lahore
8    Rafay   22     67    Karachi
9   Fatima   20     92  Islamabad

In [ ]:
df.head()

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
1    Ahmed   21     72     Lahore
2      Ali   20     91    Karachi
3    Usman   22     65  Islamabad
4    Hamza   21     78     Lahore

In [ ]:
df.tail()

      Name  Age  Marks       City
5   Ayesha   20     95    Karachi
6    Bilal   23     55  Islamabad
7  Mahnoor   21     88     Lahore
8    Rafay   22     67    Karachi
9   Fatima   20     92  Islamabad

In [ ]:
df.shape

(10, 4)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   Marks   10 non-null     int64
 3   City    10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

             Age      Marks
count  10.000000  10.000000
mean   21.000000  78.800000
std     1.054093  13.546627
min    20.000000  55.000000
25%    20.000000  68.250000
50%    21.000000  81.500000
75%    21.750000  90.250000
max    23.000000  95.000000

In [ ]:
df["Marks"]

0    85
1    72
2    91
3    65
4    78
5    95
6    55
7    88
8    67
9    92
Name: Marks, dtype: int64

In [ ]:
df["Name"]

0    Taimoor
1      Ahmed
2        Ali
3      Usman
4      Hamza
5     Ayesha
6      Bilal
7    Mahnoor
8      Rafay
9     Fatima
Name: Name, dtype: object

In [ ]:
df[["Name", "Marks"]]

      Name  Marks
0  Taimoor     85
1    Ahmed     72
2      Ali     91
3    Usman     65
4    Hamza     78
5   Ayesha     95
6    Bilal     55
7  Mahnoor     88
8    Rafay     67
9   Fatima     92

In [ ]:
df.iloc[0]

Name       Taimoor
Age             20
Marks           85
City     Islamabad
Name: 0, dtype: object

In [ ]:
df.iloc[0:3]

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
1    Ahmed   21     72     Lahore
2      Ali   20     91    Karachi

In [ ]:
df.iloc[0, 2]

np.int64(85)

In [ ]:
df[df["Marks"] > 70]

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
1    Ahmed   21     72     Lahore
2      Ali   20     91    Karachi
4    Hamza   21     78     Lahore
5   Ayesha   20     95    Karachi
7  Mahnoor   21     88     Lahore
9   Fatima   20     92  Islamabad

In [ ]:
df[df["Marks"] < 70]

    Name  Age  Marks       City
3  Usman   22     65  Islamabad
6  Bilal   23     55  Islamabad
8  Rafay   22     67    Karachi

In [ ]:
df[df["Age"] == 20]

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
2      Ali   20     91    Karachi
5   Ayesha   20     95    Karachi
9   Fatima   20     92  Islamabad

In [ ]:
df[df["City"] == "Islamabad"]

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
3    Usman   22     65  Islamabad
6    Bilal   23     55  Islamabad
9   Fatima   20     92  Islamabad

In [ ]:
df[(df["Marks"] > 80) & (df["Age"] < 21)]

      Name  Age  Marks       City
0  Taimoor   20     85  Islamabad
2      Ali   20     91    Karachi
5   Ayesha   20     95    Karachi
9   Fatima   20     92  Islamabad

In [ ]:
df["Marks"].mean()

np.float64(78.8)

In [ ]:
df["Marks"].max()

95

In [ ]:
df["Marks"].min()

55

In [ ]:
df["Marks"].sum()

np.int64(788)

In [ ]:
df["Marks"].median()

81.5

In [ ]:
import numpy as np

In [ ]:
numbers = np.array([11, 12, 13, 14, 15])

In [ ]:
print(numbers)

[11 12 13 14 15]

In [ ]:
np.mean(numbers)

np.float64(13.0)

In [ ]:
np.min(numbers)

np.int64(11)

In [ ]:
np.max(numbers)

np.int64(15)

In [ ]:
np.sum(numbers)

np.int64(65)

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2